name = "AllometricModels"
uuid = "1c853ebb-f589-4e8a-a6f3-211670fabf15"
authors = ["Marcos Daniel da Silva <marcosdasilva@5a.tec.br> and contributors"]
version = "1.0.0-DEV"

[deps]
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
GLM = "1.9.0"
Logging = "1.11.0"
MixedModels = "5.1.0"
Reexport = "1.2.2"
StatsModels = "0.7.7"
Tables = "1.12.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
