name = "AllometricModels"
uuid = "1c853ebb-f589-4e8a-a6f3-211670fabf15"
version = "1.0.0-DEV"
authors = ["Marcos Daniel da Silva <marcosdasilva@5a.tec.br> and contributors"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"

[extensions]
GLMExt = "GLM"

[compat]
Combinatorics = "1.0.3"
Distributions = "0.25.122"
HypothesisTests = "0.11.6"
LinearAlgebra = "1.12.0"
Revise = "3.12.3"
StatsAPI = "1.7.1"
StatsBase = "0.34.8"
StatsModels = "0.7.7"
Tables = "1.12.1"
julia = "1.12.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
