name = "AllometricModels"
uuid = "1c853ebb-f589-4e8a-a6f3-211670fabf15"
version = "1.0.0-DEV"
authors = ["Marcos Daniel da Silva <marcosdasilva@5a.tec.br> and contributors"]

[deps]
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
GLM = "1.9.0"
MixedModels = "5.1.0"
StatsModels = "0.7.7"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
